// default package
// Generated Apr 27, 2014 10:29:38 AM by Hibernate Tools 3.4.0.CR1

package dbmodel;
import java.util.HashSet;
import java.util.Set;

/**
 * Vozilo generated by hbm2java
 */
public class Vozilo  implements java.io.Serializable {


     private Integer idvozila;
     private Kategorija kategorija;
     private String marka;
     private String model;
     private Integer cena;
     private Integer godinaproizvodnje;
     private String boja;
     private Set prodajas = new HashSet(0);

    public Vozilo() {
    }

	
    public Vozilo(Kategorija kategorija) {
        this.kategorija = kategorija;
    }
    public Vozilo(Kategorija kategorija, String marka, String model, Integer cena, Integer godinaproizvodnje, String boja, Set prodajas) {
       this.kategorija = kategorija;
       this.marka = marka;
       this.model = model;
       this.cena = cena;
       this.godinaproizvodnje = godinaproizvodnje;
       this.boja = boja;
       this.prodajas = prodajas;
    }
   
    public Integer getIdvozila() {
        return this.idvozila;
    }
    
    public void setIdvozila(Integer idvozila) {
        this.idvozila = idvozila;
    }
    public Kategorija getKategorija() {
        return this.kategorija;
    }
    
    public void setKategorija(Kategorija kategorija) {
        this.kategorija = kategorija;
    }
    public String getMarka() {
        return this.marka;
    }
    
    public void setMarka(String marka) {
        this.marka = marka;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public Integer getCena() {
        return this.cena;
    }
    
    public void setCena(Integer cena) {
        this.cena = cena;
    }
    public Integer getGodinaproizvodnje() {
        return this.godinaproizvodnje;
    }
    
    public void setGodinaproizvodnje(Integer godinaproizvodnje) {
        this.godinaproizvodnje = godinaproizvodnje;
    }
    public String getBoja() {
        return this.boja;
    }
    
    public void setBoja(String boja) {
        this.boja = boja;
    }
    public Set getProdajas() {
        return this.prodajas;
    }
    
    public void setProdajas(Set prodajas) {
        this.prodajas = prodajas;
    }




}


