/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2015-12-13 13:12:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"demo.css\" media=\"all\" />\r\n");
      out.write("<script src=\"./scripts/jquery-1.11.3.js\"></script>\r\n");
      out.write("<title>Dobro dosli u AutoKucu</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<h1><span>AUTO KUCA</span>\t\t\t\r\n");
      out.write("\t\t\t\tBoris Zaharic\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("            </header>  \r\n");
      out.write("<div  class=\"form\">\r\n");
      out.write("<form id=\"contactform\" method=\"post\" action=\"../AutoKuca/LoginServlet\" class=\"login\">\r\n");
      out.write("    <p class=\"contact\">\r\n");
      out.write("      <label for=\"username\">Username:</label>\r\n");
      out.write("      \r\n");
      out.write("    </p>\r\n");
      out.write("    <input id=\"username\" type=\"text\" name=\"username\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("    <p class=\"contact\">\r\n");
      out.write("      <label for=\"password\">Password:</label>\r\n");
      out.write("      \r\n");
      out.write("    </p>\r\n");
      out.write("    <input id=\"password\" type=\"password\" name=\"password\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("    <input type=\"submit\" value=\"Ulogujte se!\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div align=\"center\" id=\"poruka\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${poruka}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div><br>\r\n");
      out.write("  </form>\r\n");
      out.write("  <fb:login-button scope=\"public_profile,email\" onlogin=\"checkLoginState();\">\r\n");
      out.write("</fb:login-button>\r\n");
      out.write("<div id='status'></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("(function(d, s, id) {\r\n");
      out.write("    var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("    if (d.getElementById(id)) return;\r\n");
      out.write("    js = d.createElement(s); js.id = id;\r\n");
      out.write("    js.src = \"//connect.facebook.net/en_US/sdk.js\";\r\n");
      out.write("    fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("  }(document, 'script', 'facebook-jssdk'));\r\n");
      out.write("  \r\n");
      out.write("  window.fbAsyncInit = function() {\r\n");
      out.write("  FB.init({\r\n");
      out.write("    appId      : '1649281665320108',\r\n");
      out.write("    cookie     : true,  // enable cookies to allow the server to access \r\n");
      out.write("                        // the session\r\n");
      out.write("    xfbml      : true,  // parse social plugins on this page\r\n");
      out.write("    version    : 'v2.5' // use version 2.2\r\n");
      out.write("  });\t\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function checkLoginState() {\r\n");
      out.write("\t    FB.getLoginStatus(function(response) {\r\n");
      out.write("\t      statusChangeCallback(response);\r\n");
      out.write("\t    });\r\n");
      out.write("\t  }\r\n");
      out.write("  \r\n");
      out.write("  function statusChangeCallback(response) {\r\n");
      out.write("\t    // The response object is returned with a status field that lets the\r\n");
      out.write("\t    // app know the current login status of the person.\r\n");
      out.write("\t    // Full docs on the response object can be found in the documentation\r\n");
      out.write("\t    // for FB.getLoginStatus().\r\n");
      out.write("\t    if (response.status === 'connected') {\r\n");
      out.write("\t      // Logged into your app and Facebook.\r\n");
      out.write("\t      var accessToken = response.authResponse.accessToken;\r\n");
      out.write("\t      $.ajax({\r\n");
      out.write("\t    \t  url:'LoginServlet',\r\n");
      out.write("\t    \t  data: {'access-token': accessToken},\r\n");
      out.write("\t    \t  success: function(){\r\n");
      out.write("\t    \t\t  window.location = 'JSPStranice/Autokuca.jsp';\r\n");
      out.write("\t    \t  }\r\n");
      out.write("\t      })\r\n");
      out.write("\t     \tconsole.log(accessToken)\r\n");
      out.write("\t    } else if (response.status === 'not_authorized') {\r\n");
      out.write("\t      // The person is logged into Facebook, but not your app.\r\n");
      out.write("\t      document.getElementById('status').innerHTML = 'Please log ' +\r\n");
      out.write("\t        'into this app.';\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t      // The person is not logged into Facebook, so we're not sure if\r\n");
      out.write("\t      // they are logged into this app or not.\r\n");
      out.write("\t      document.getElementById('status').innerHTML = 'Please log ' +\r\n");
      out.write("\t        'into Facebook.';\r\n");
      out.write("\t    }\r\n");
      out.write("\t  }\r\n");
      out.write("  </script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
